# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

invC <- function(M) {
    .Call(`_mypkgr_invC`, M)
}

#'@export
mvnpdfsmartC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_mypkgr_mvnpdfsmartC`, x, mean, varcovM, Log)
}

timesTwo <- function(x) {
    .Call(`_mypkgr_timesTwo`, x)
}

